services:
  postgres:
    image: postgres:18
    container_name: node_ts_postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: passw
      POSTGRES_DB: app_db
    ports:
      - "3002:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - node_ts_pg

  node_ts: 
    build:  # when compose up, automatically build app with flag --build.
      context: .
      dockerfile: Dockerfile
    image: node_ts_multi_stages:latest  # this name will be assigned to the new built image
    container_name: node_ts_app
    env_file:  # mount the .env at runtime (when we do: docker compose up)
      - .env
    ports:
      - "3001:3000"
    networks:
      - node_ts_pg
    depends_on:  # make sure service node_ts run after service postgres
      - postgres

volumes:
  pgdata:
    name: pgdata

networks:
  node_ts_pg:
    name: node_ts_pg
    driver: bridge
